<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.6 on win32)" generated="20201106 21:53:02.165" rpa="false">
<suite id="s1" name="GenerateApiKey" source="C:\Users\Pichau\Desktop\Docs Lucas\python\Teste Prime Control\Teste-Prime-Control\Robots\GenerateApiKey.robot">
<test id="s1-t1" name="Generate API KEY">
<kw name="Open Browser To LOGIN Page">
<arguments>
<arg>${endereco}</arg>
</arguments>
<msg timestamp="20201106 21:53:02.369" level="FAIL">Variable '${endereco}' not found.</msg>
<status status="FAIL" starttime="20201106 21:53:02.369" endtime="20201106 21:53:02.369"></status>
</kw>
<doc>Fazer o login na pagina e gerar a key para a api</doc>
<status status="FAIL" starttime="20201106 21:53:02.368" endtime="20201106 21:53:02.370" critical="yes">Variable '${endereco}' not found.</status>
</test>
<status status="FAIL" starttime="20201106 21:53:02.168" endtime="20201106 21:53:02.377"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="GenerateApiKey">GenerateApiKey</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20201106 21:53:02.166" level="ERROR">Variable file '\Libraries\config.py' does not exist.</msg>
<msg timestamp="20201106 21:53:02.367" level="ERROR">Error in file 'C:\Users\Pichau\Desktop\Docs Lucas\python\Teste Prime Control\Teste-Prime-Control\Robots\GenerateApiKey.robot' on line 3: Test library 'Libraries\config.py' does not exist.</msg>
</errors>
</robot>
